### ISSUE TITLE
pull_number undefined when action is running on push to master branch

### ISSUE THREAD

**Issue by ppalucha** [ad1992/clean-commit-action#5]
Hi, we have action running fine on PRs, but when merging PR to master, the action fails with message:

```
Error: Action failed with error: Empty value for parameter 'pull_number': undefined
```

The workflow we use is just simple:
```
jobs:
  check-commit:
    runs-on: self-hosted-fleet
    steps:
      - name: Check commit message
        uses: ad1992/clean-commit-action@v0.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
